# Generated by Django 3.0.8 on 2020-07-13 11:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=tinymce.models.HTMLField(default='paulmburu08@gmail.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=tinymce.models.HTMLField(default='0758845666'),
            preserve_default=False,
        ),
    ]
