# Generated by Django 3.0.8 on 2020-07-13 15:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0003_auto_20200713_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=tinymce.models.HTMLField(default='Paul'),
            preserve_default=False,
        ),
    ]
