# Generated by Django 3.0.8 on 2020-07-14 21:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meritapp', '0005_auto_20200714_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
